# Generated by Django 4.0.3 on 2022-05-30 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('Nearby_University', models.CharField(default='Some Nearby University', max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('seater', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('hostel_type', models.CharField(choices=[('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel')], default='Male', max_length=100)),
                ('food_facility', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('laundary_facility', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('internet_facility', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('photo1', models.ImageField(default='photo1', upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(default='photo2', upload_to='photos/%Y/%m/%d/')),
                ('realtor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
