# Generated by Django 4.0.3 on 2022-04-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0002_remove_listing_realtor_listing_realtor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to='accounts.account'),
        ),
    ]
