# Generated by Django 4.0.3 on 2022-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
    ]
