# Generated by Django 4.0.3 on 2022-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Tenant', 'Tenant'), ('Realtor', 'Realtor')], default='Tenant', max_length=100)),
                ('photo', models.ImageField(default='photo', upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
