# Generated by Django 4.0.3 on 2022-05-30 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date_time', models.DateTimeField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('is_approved', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('realtor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
