# Generated by Django 4.0.3 on 2022-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(),
        ),
    ]
