# Generated by Django 4.0.3 on 2022-04-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0003_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='accounts.account'),
        ),
    ]
