# Generated by Django 4.0.3 on 2022-04-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0004_booking_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='realtor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to='accounts.account'),
        ),
    ]
