# Generated by Django 4.0.3 on 2022-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_approved',
        ),
    ]
