# Generated by Django 4.0.3 on 2022-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100),
        ),
    ]
