# Generated by Django 4.0.3 on 2022-04-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listingsFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingfeedback',
            name='realtor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
