# Generated by Django 4.0.3 on 2022-04-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingsFeedback', '0002_listingfeedback_realtor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingfeedback',
            old_name='realtor_id',
            new_name='tenant_id',
        ),
    ]
